# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: Job1
    - script: echo Hello, world!
      displayName: 'Run a one-line script'
  - job: Job2
- stage: QAStage
  jobs:
  - job: Job1ofQAStage
  - script: echo Hello, world!
    displayName: 'Run a one-line script'
  - job: Job2ofQAStage
- stage: TestStage
  jobs:
  - job: Job1ofTeststage
  - script: echo Hello, world!
    displayName: 'Run a one-line script'
  - job: Job2ofTestStage
- stage: ProdStage
  jobs:
  - job: Job1ofProdStage
  - script: echo Hello, world!
    displayName: 'Run a one-line script'
  - job: Job2ofProdStage
 


